### ISSUE TITLE
update API 3.0.0

### ISSUE THREAD

**Issue by teracube** [CookieCode/WorldBorder#1]
please update API 3.0.0

**Comment by CookieCode** [comment]
It's updated ! https://github.com/CookieCode/WorldBorder/commit/6834f5147153cff781eabd4ee794151ce5f9165a

**Comment by CookieCode** [comment]
It's updated https://github.com/CookieCode/WorldBorder/commit/6834f5147153cff781eabd4ee794151ce5f9165a

**Comment by CookieCode** [comment]
I'ts updated.
